version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    image: dinopedia
    environment:
      APP_DEBUG_MODE: "True"
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_NAME: dinopedia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    entrypoint: ""
    command: "python dinopedia/manage.py runserver"
    ports:
      - 8002:8000
    volumes:
      - ./src:/usr/src/app/src
      - ./tests:/usr/src/app/tests
      - ./scripts:/usr/src/app/scripts
      - ./pyproject.toml:/usr/src/app/pyproject.toml
      - ./poetry.lock:/usr/src/app/poetry.lock
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: dinopedia
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
